name: Static Code Analysis

on: push

jobs:
  static-code-analysis:
    runs-on: ubuntu-latest
    name: Static Code Analysis
    env:
      REL_SRC_DIR_PATH: ./src
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch

      - name: mypy
        run: |
          mypy \
            --show-error-codes \
            --disable-error-code import \
            "${REL_SRC_DIR_PATH}"

      - name: pylint
        run: |
          pylint "${REL_SRC_DIR_PATH}"

      - name: flake8
        run: |
          flake8 --config .flake8

      - name: bandit
        run: |
          bandit -r "${REL_SRC_DIR_PATH}"
