name: Unit and Integration Tests

on: push

jobs:
  unit_and_int_tests:
    runs-on: ubuntu-latest
    name: Unit and Integration Tests
    env:
      REL_SRC_DIR_PATH: ./src
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5
          cache: 'pip' # caching pip dependencies

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          pytest \
            --cov="${REL_SRC_DIR_PATH}" \
            --cov-report=xml
